// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GF_ChairProperty","status":true,"description":"","parameters":{}},
{"name":"GF_PreLoadEventBM","status":true,"description":"","parameters":{}},
{"name":"GF_Fuki","status":true,"description":"","parameters":{}}
];
